// Imports

import React    from 'react';
import Footer   from '../components/layouts/Footer';




// ----------------------------------------------------------------------------------------------------------------------------------

// Privacy Policy Page

const PrivacyPolicy = () => {

    return (

        <div>
            <header className="header header__faq">
                <div className="header__text-box">
                    <h1 className="heading-primary">
                        <span className="heading-primary__sub">
                            Privacy Policy
                        </span>
                    </h1>
                </div>
            </header>

            <main>
                <section className="section-privacy">
                    <div className="row">
                        <p className="paragraph">Last updated: August 17, 2020</p>
                        <p className="paragraph">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                        <p className="paragraph">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
                        </p>
                    </div>

                    <div className="row">
                        <h1 className="heading-primary--sub">Interpretation and Definitions</h1>
                    </div>

                    <div className="row">
                        <div className="col-1-of-4">
                            <h2 className="heading-secondary heading-secondary-privacy">
                                Interpretation
                            </h2>
                        </div>

                        <div className="col-3-of-4">
                            <p className="paragraph">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                            </p>
                        </div>
                    </div>

                    <div className="row">
                        <div className="col-1-of-4">
                            <h2 className="heading-secondary heading-secondary-privacy">
                                Definitions
                            </h2>
                        </div>

                        <div className="col-3-of-4">
                            <p className="paragraph">
                                For the purposes of this Privacy Policy:
                            </p>
                            <p className="paragraph paragraph--privacy">
                                <ul>
                                    <li><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</li>
                                    <li><b>Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Empire 534, Pasadena, CA.</li>
                                    <li><b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                                    <li><b>Country</b> refers to: California, United States</li>
                                    <li><b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                                    <li><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</li>
                                    <li><b>Service</b> refers to the Website.</li>
                                    <li><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                                    <li><b>Third-party Social Services</b> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                                    <li><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                                    <li><b>Website</b> refers to Empire 534, accessible from <a href="http://www.empire534.la" className="home-link">http://www.empire534.la</a></li>
                                    <li><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                                </ul>
                            </p>
                        </div>
                    </div>

                    <div className="row">
                        <h1 className="heading-primary--sub">Collecting and Using Your Personal Data</h1>
                    </div>

                    <div className="row">
                        <div className="col-1-of-4">
                            <h2 className="heading-secondary heading-secondary-privacy">
                                Types of Data Collected
                            </h2>
                        </div>

                        <div className="col-3-of-4">
                            <h3 className="heading-tertiary heading-tertiary-privacy">Personal Data</h3>
                            <p className="paragraph">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                            <p className="paragraph paragraph--privacy">
                                <ul>
                                    <li>Email Address</li>
                                    <li>First Name and Last Name</li>
                                    <li>Phone Number</li>
                                    <li>Usage Data</li>
                                </ul>
                            </p>

                            <h3 className="heading-tertiary heading-tertiary-privacy">Tracking Technologies and Cookies</h3>
                            <p className="paragraph">Usage Data is collected automatically when using the Service.</p>
                            <p className="paragraph">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                            <p className="paragraph">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                            <p className="paragraph">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

                            <h3 className="heading-tertiary">Usage Data</h3>
                            <p className="paragraph">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
                            <p className="paragraph">You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
                            <p className="paragraph">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser. Learn more about cookies: All About Cookies.</p>
                            <p className="paragraph">We use both session and persistent Cookies for the purposes set out below:</p>
                            <p className="paragraph paragraph--privacy">
                                <ul>
                                    <li>
                                        <b>Necessary / Essential Cookies</b>
                                        <br/>
                                        Type: Session Cookies
                                        <br/>
                                        Administered by: Us
                                        <br/>
                                        Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                                    </li>
                                    <li>
                                        <b>Cookies Policy / Notice Acceptance Cookies</b>
                                        <br/>
                                        Type: Persistent Cookies
                                        <br/>
                                        Administered by: Us
                                        <br/>
                                        Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                                    </li>
                                    <li>
                                        <b> Functionality / Cookies</b>
                                        <br/>
                                        Type: Persistent Cookies
                                        <br/>
                                        Administered by: Us
                                        <br/>
                                        Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                                    </li>
                                </ul>
                            </p>
                            <p className="paragraph">
                                For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
                            </p>
                        </div>
                    </div>

                    <div className="row">
                        <div className="col-1-of-4">
                            <h2 className="heading-secondary heading-secondary-privacy">
                                Use of Your Personal Data
                            </h2>
                        </div>
                    </div>
                </section>
            </main>

            <Footer/>
        </div>

    )

}



// ----------------------------------------------------------------------------------------------------------------------------------

// Exports

export default PrivacyPolicy